### ISSUE TITLE
How can I import this plugin?

### ISSUE THREAD

**Issue by TacticalSpoon331** [amoraschi/mineflayer-elytrafly#2]
Error thrown when importing plugin:

const elytrafly = require('mineflayer-elytrafly')
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/mineflayer-elytrafly/dist/index.js from elytraTest.js not supported.
Instead change the require of index.js in elytraTest.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (elytraTest.js:2:19) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by amoraschi** [comment]
It uses ES6 syntax, so you should import it like this:

```js
import { elytrafly } from 'mineflayer-elytrafly'
```

**Comment by TacticalSpoon331** [comment]
Now I just get:

(node:13219) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
elytraTest.js:2
import { elytrafly } from 'mineflayer-elytrafly'
^^^^^^

SyntaxError: Cannot use import statement outside a module

Sorry, trying to relearn JS

**Comment by amoraschi** [comment]
The error tells you what to do, part of learning a language is learning to understand errors

**Comment by TacticalSpoon331** [comment]
Not trying to be that guy that goes straight to GitHub without investigating any errors first. I tried marking the script as a module but that just led to more problems. This might be asking too much but are there any example projects I could take a look at to make sure it's not my node installation?

**Comment by amoraschi** [comment]
It's not your Node installation, what's your error?
