### ISSUE TITLE
Make the plugin CommonJS instead of a ES module.

### ISSUE THREAD

**Issue by KhaoDoesDev** [amoraschi/mineflayer-elytrafly#3]
In the title.

**Comment by amoraschi** [comment]
> In the title.

Why?

**Comment by KhaoDoesDev** [comment]
I mean u can make it compatible with both but most people have their bots in CommonJS so it's only a tiny bit of people who can use this plugin. Including that most plugins are compatible with both anyways.

**Comment by ghost** [comment]
I loved to see this happen.

**Comment by amoraschi** [comment]
@Khaogamermain01 @Razorr222 

PRs are open. I'm busy these days but will take a look once I'm free

**Comment by tomas-kucera** [comment]
I am really struggling with this. I am quite new to JS and TS and all this complexity is driving me crazy.

I keep getting this! `Error [ERR_REQUIRE_ESM]: require() of ES Module` if I try to change it to dynamic, I get other errors.

I am trying to use it with the mineflayer and mineflayer-pathfinder.

Could anyone, please, post a code that will allow to import this? Searched the whole web, but just could get it passed the import.

Thanks in advance!

**Comment by amoraschi** [comment]
Updated package
